name: dcase
channels:
  - defaults
dependencies:
  - python
  - ipykernel
  - lightning
  - pandas
  - joblib
  - numpy
  - scikit-learn
  - scipy
  - pytorch-nightly::pytorch
  - torchaudio
  - torchvision
  - pip
  - pip:
    - torchinfo
    - transformers
    - wandb
    - librosa
    - git+https://github.com/kymatio/murenn